name: Report size

on:
  pull_request:
    # TEMP
    types: [opened, synchronize]
    # paths:
    #   - 'src/**'
    #   - 'package.json'

jobs:
  treeshaking:
    name: Tree-shaking
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v3
      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build-module
      - name: === Test tree-shaking ===
        run: npm run test-treeshake
      - name: Read tree-shaken size
        id: read-size
        run: |
          FILESIZE=$(stat --format=%s test/treeshake/index.bundle.min.js)
          gzip -k test/treeshake/index.bundle.min.js
          FILESIZE_GZIP=$(stat --format=%s test/treeshake/index.bundle.min.js.gz)
          echo "FILESIZE=$FILESIZE" >> $GITHUB_OUTPUT
          echo "FILESIZE_GZIP=$FILESIZE_GZIP" >> $GITHUB_OUTPUT

      - name: Checkout base branch
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.base.ref }}
          repository: ${{ github.event.pull_request.base.repo.full_name }}
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build-module
      - name: === Test tree-shaking ===
        run: npm run test-treeshake
      - name: Read tree-shaken size
        id: read-size-base
        run: |
          FILESIZE_BASE=$(stat --format=%s test/treeshake/index.bundle.min.js)
          echo "FILESIZE_BASE=$FILESIZE_BASE" >> $GITHUB_OUTPUT
      - name: Compute diff
        id: compute-diff
        run: |
          FILESIZE=${{ steps.read-size.outputs.FILESIZE }}
          FILESIZE_BASE=${{ steps.read-size-base.outputs.FILESIZE_BASE }}
          FILESIZE_DIFF=$(echo "scale=1; ($FILESIZE - $FILESIZE_BASE) * 100 / $FILESIZE_BASE" | bc)
          echo "FILESIZE_DIFF=$FILESIZE_DIFF" >> $GITHUB_OUTPUT

      - name: Find existing comment
        uses: peter-evans/find-comment@v2
        id: find-comment
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: 'github-actions[bot]'
          body-includes: Bundle size
      - name: Comment on PR
        uses: peter-evans/create-or-update-comment@v2
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-id: ${{ steps.find-comment.outputs.comment-id }}
          edit-mode: replace
          body: |
            ### 📦 Bundle size after tree-shaking
            | Filesize | Gzipped | Diff |
            |----------|---------|------|
            | ${{ steps.read-size.outputs.FILESIZE }} | ${{ steps.read-size.outputs.FILESIZE_GZIP }} | ${{ steps.compute-diff.outputs.FILESIZE_DIFF }}% |
